# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "v4l2loopback" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [
    v4l2loopback
  ];

  boot.extraModprobeConfig = ''
    options v4l2loopback devices=1 video_nr=10 card_label="WaydroidCam" exclusive_caps=1
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0e8f14bc-f593-48f3-ba1f-132ad8dd5e93";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/08EF-3625";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =[
    { device = "/dev/disk/by-uuid/7479d7b5-8a33-474e-8aa5-c1c45b84113d"; }
    {
      device = "/var/lib/swapfile";
      size = 32768;
    }
  ];

  fileSystems."/storage" = {
    device = "/dev/disk/by-uuid/64337ddc-958e-481e-aa1b-bb605115bd6c";
    fsType = "ext4";
    options = [ "defaults" "nofail" "x-systemd.device-timeout=5s" ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  powerManagement.cpuFreqGovernor = "performance";
}
